[tools]
"cargo:jj-starship" = "latest"
"github:anomalyco/opencode" = "latest"
go = "latest"
helm = "latest"
java = "latest"
k9s = "latest"
kubectl = "latest"
kotlin = "latest"
node = "lts"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:sfw" = "latest"
"npm:skills" = "latest"
"npm:hunkdiff" = "latest"
"pipx:graphifyy" = "latest"
"pipx:sqlit-tui" = "latest"
pipx = "latest"
poetry = "latest"
python = "3.12"
ruby = "latest"
rust = "latest"
terraform = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
zig.use_community_mirrors = true
