[tools]
"cargo:jj-starship" = "latest"
elixir = "latest"
erlang = "latest"
flutter = "latest"
"github:anomalyco/opencode" = "latest"
"github:odin-lang/Odin" = "latest"
go = "latest"
"go:github.com/bootdotdev/bootdev" = "latest"
helm = "latest"
java = "latest"
k9s = "latest"
kubectl = "latest"
kotlin = "latest"
node = "lts"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:sfw" = "latest"
"npm:skills" = "latest"
"npm:hunkdiff" = "latest"
odin = { version = "latest", exe = "odin" }
"pipx:graphifyy" = "latest"
"pipx:sqlit-tui" = "latest"
pipx = "latest"
poetry = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
terraform = "latest"
uv = "latest"
zig = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
minimum_release_age = "7d"
zig.use_community_mirrors = true
