---
username: "{{ lookup('env', 'USER') }}"
git_name: "my name"
git_email: "my@email.com"

sudoers_custom_config: |
  #Defaults env_reset
  Defaults !secure_path
  Defaults    env_keep += "XDG_CONFIG_HOME HOME"
  Defaults env_keep += "EDITOR VISUAL"
  #Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  #Defaults env_keep += "PATH"
  #Defaults env_keep += "HOME"
  # This fixes CVE-2005-4890 and possibly breaks some versions of kdesu
  # (#1011624, https://bugs.kde.org/show_bug.cgi?id=452532)
  Defaults use_pty

pacman_pkgs:
  - ansible
  - bind
  - birdfont
  - blanket
  - brave-bin
  - btrfs-assistant
  - cachyos-plymouth-theme
  - cachyos-snapper-support
  - cachyos-themes-sddm
  - cliphist
  - converseen
  - cups
  - cups-filters
  - cups-pdf
  - discord
  - docker
  - docker-buildx
  - docker-compose
  - foomatic-db
  - foomatic-db-engine
  - foomatic-db-gutenprint-ppds
  - foomatic-db-nonfree
  - foomatic-db-nonfree-ppds
  - foomatic-db-ppds
  - fail2ban
  - fprintd
  - fuzzel
  - ghostscript
  - github-cli
  - glow
  - gnupg
  - gsfonts
  - gst-plugin-va
  - gum
  - gutenprint
  - handbrake
  - headscale
  - hplip
  - imv
  - intel-media-driver
  - intel-media-sdk
  - jujutsu
  - kdenlive
  - keepassxc
  - keychain
  - kitty
  - lazydocker
  - lazygit
  - lazyjj
  - lib32-mesa
  - lib32-opencl-mesa
  - lib32-vulkan-intel
  - libmythes
  - librecad
  - libreoffice-fresh
  - libyaml
  - limine
  - limine-mkinitcpio-hook
  - limine-snapper-sync
  - linux-headers
  - llvm
  - lsof
  - luarocks
  - markdownlint-cli2
  - mise
  - mousetweaks
  - movit
  - neovim
  - noto-color-emoji-fontconfig
  - obsidian
  - onlyoffice-bin
  - opam
  - opencl-mesa
  - opencolorio
  - opencv
  - opus-tools
  - os-prober
  - pandoc-cli
  - pass
  - prettier
  - python-pyqt5
  - python-reportlab
  - qbittorrent
  - qt5-graphicaleffects
  - scrcpy
  - seahorse
  - shelly
  - shortwave
  - signal-desktop
  - snapper
  - soundconverter
  - sox
  - sqlfluff
  - starship
  - stow
  - stylua
  - system-config-printer
  - television
  - tlp
  - tlp-rdw
  - tlpui
  - tmux
  - torbrowser-launcher
  - transmageddon
  - tree-sitter
  - ttf-jetbrains-mono-nerd
  - ttf-roboto
  - ufw-extras
  - unixodbc
  - v4l2loopback-dkms
  - virt-manager
  - virtualbox
  - vlc
  - vulkan-intel
  - waybar
  - whois
  - wtype
  - xf86-input-wacom
  - yay
  - yazi
  - yubikey-manager
  - zellij
  - zen-browser-bin
  - zoxide

yay_pkgs:
  - digimend-kernel-drivers-dkms-git
  - input-remapper-git
  - jack
  - localsend-bin
  - nirimod-git
  - sesh-bin
  - snapd
  - ttf-nerd-fonts-meta
