---
- name: Copy dotfiles first round
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/dotfiles"
    dest: "~/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    directory_mode: '0755'
  become: true
  become_user: "{{ username }}"
  register: dotfirst

- name: Noctalia settings first round
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/noctalia-settings.j2"
    dest: "~/dotfiles/noctalia/.config/noctalia/settings.json"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  become: true
  become_user: "{{ username }}"
  when: dotfirst.changed
  register: noctaliafirst

- name: Stow dotfiles
  ansible.builtin.command:
    cmd: "~/dotfiles/dotfiles.sh"
  register: dotstow

- name: Copy dotfiles final round
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/dotfiles"
    dest: "~/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    directory_mode: '0755'
  become: true
  become_user: "{{ username }}"
  when: dotstow.changed

- name: Noctalia settings second round
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/noctalia-settings.j2"
    dest: "~/dotfiles/noctalia/.config/noctalia/settings.json"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  become: true
  become_user: "{{ username }}"
  when: dotstow.changed
