---
- name: Copy glitch plymouth animation
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/plymouth/glitch"
    dest: /usr/share/plymouth/themes/
  become: true

- name: Get current plymouth theme
  ansible.builtin.command:
    cmd: plymouth-set-default-theme
  register: current_theme
  changed_when: false

- name: Set glitch plymouth theme
  ansible.builtin.command:
    cmd: "plymouth-set-default-theme -R glitch"
  become: true
  when: current_theme.stdout != 'glitch'
