---
- name: Check if lazyvim installed
  ansible.builtin.stat:
    path: "{{ ansible_facts['user_dir'] ~ '/.config/nvim/lua/config/lazy.lua' }}"
  register: lazyvim

- name: install lazyvim
  ansible.builtin.shell: |
    # required
    mv ~/.config/nvim{,.bak} 2>/dev/null || true

    # optional but recommended
    mv $HOME/.local/share/nvim{,.bak} 2>/dev/null || true
    mv $HOME/.local/state/nvim{,.bak} 2>/dev/null || true
    mv $HOME/.cache/nvim{,.bak} 2>/dev/null || true
    git clone https://github.com/LazyVim/starter $HOME/.config/nvim
    rm -rf $HOME/.config/nvim/.git
  when: not lazyvim.stat.exists
